# -*- coding: utf-8 -*-
"""hw1p3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nf9-rR8ZAsuaDICLcKD6ObL-YM073jX-
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images.shape

len(train_images)

train_images.ndim

train_images.dtype

train_labels

train_labels.shape

len(train_labels)

digit_0 = train_images[0]

digit_0.shape

plt.figure(figsize=(4, 4))
plt.imshow(digit_0)
plt.show()

label_0 = train_labels[0]
label_0

plt.figure(figsize=(4, 4))
digit_1 = train_images[1]
plt.imshow(digit_1)
plt.show()

label_1 = train_labels[1]
label_1

zeros = np.zeros((60000, 28, 28))
ones = np.zeros((60000, 28, 28))
twos = np.zeros((60000, 28, 28))
threes = np.zeros((60000, 28, 28))
fours = np.zeros((60000, 28, 28))
fives = np.zeros((60000, 28, 28))
sixes = np.zeros((60000, 28, 28))
sevens = np.zeros((60000, 28, 28))
eights = np.zeros((60000, 28, 28))
nines = np.zeros((60000, 28, 28))

i0 = 0
i1 = 0
i2 = 0
i3 = 0
i4 = 0
i5 = 0
i6 = 0
i7 = 0
i8 = 0
i9 = 0

for i in train_labels:
  if train_labels[i] == 0:
    zeros[i0] = train_images[i]
    i0 += 1
#   elif train_labels[i] == 1:
#     zeros[i0] = train_images[i]
#     i0 += 1
#   elif train_labels[i] == 2:
#     zeros[i0] = train_images[i]
#     i0 += 1
#   elif train_labels[i] == 3:
#     zeros[i0] = train_images[i]
#     i0 += 1
#   elif train_labels[i] == 4:
#     zeros[i0] = train_images[i]
#     i0 += 1
#   elif train_labels[i] == 5:
#     fives[i5] = train_images[i]
#     i5 += 1
#   elif train_labels[i] == 6:
#     sixes[i6] = train_images[i]
#     i6 += 1
#   elif train_labels[i] == 7:
#     zeros[i0] = train_images[i]
#     i0 += 1
#   elif train_labels[i] == 8:
#     zeros[i0] = train_images[i]
#     i0 += 1
#   elif train_labels[i] == 9:
#     zeros[i0] = train_images[i]
#     i0 += 1
#   else:
#     print('in else')

zeros = np.resize(zeros, (i0, 28, 28))
ones = np.resize(ones, (i1, 28, 28))
twos = np.resize(twos, (i2, 28, 28))
threes = np.resize(threes, (i3, 28, 28))
fours = np.resize(fours, (i4, 28, 28))
fives = np.resize(fives, (i5, 28, 28))
sixes = np.resize(sixes, (i6, 28, 28))
sevens = np.resize(sevens, (i7, 28, 28))
eights = np.resize(eights, (i8, 28, 28))
nines = np.resize(nines, (i9, 28, 28))

zero_avg = np.mean(zeros, axis=0)
one_avg = np.mean(ones.tolist(), axis=0)
two_avg = np.mean(twos.tolist(), axis=0)
three_avg = np.mean(threes.tolist(), axis=0)
four_avg = np.mean(fours.tolist(), axis=0)
five_avg = np.mean(fives.tolist(), axis=0)
six_avg = np.mean(sixes.tolist(), axis=0)
seven_avg = np.mean(sevens.tolist(), axis=0)
eight_avg = np.mean(eights.tolist(), axis=0)
nine_avg = np.mean(nines.tolist(), axis=0)

plt.figure(figsize=(4, 4))
plt.imshow(zero_avg)
plt.show()